package main

import (
	"encoding/json"
	"strings"
)

// The site runs no JavaScript and loads nothing from other origins.
// metaCSP is repeated in every page's <meta> so the policy holds even if a
// host drops the header; frame-ancestors only works as a header.
const (
	metaCSP = "default-src 'none'; style-src 'self'; img-src 'self'; font-src 'self'; base-uri 'none'; form-action 'none'"
	pageCSP = metaCSP + "; frame-ancestors 'none'"
	// Demo reports carry their own strict, hash-based CSP in a <meta> tag.
	// The header adds only what a <meta> policy cannot express.
	demoCSP = "frame-ancestors 'none'"
)

type header struct{ Key, Value string }

// rule applies headers to one URL pattern. Patterns use Cloudflare's
// syntax; vercelSource converts them.
type rule struct {
	Pattern string
	Headers []header
}

var common = []header{
	{"X-Content-Type-Options", "nosniff"},
	{"Referrer-Policy", "no-referrer"},
	{"Permissions-Policy", "camera=(), microphone=(), geolocation=(), payment=(), usb=()"},
	{"Cross-Origin-Opener-Policy", "same-origin"},
	{"Strict-Transport-Security", "max-age=63072000"},
}

// rules lists every header rule. Pages get the site CSP individually rather
// than through a catch-all, and demo reports live under /reports/, so no
// response ever matches two policies on either host.
func rules() []rule {
	out := []rule{{"/*", common}}
	for _, p := range pages {
		out = append(out, rule{p.Path, []header{{"Content-Security-Policy", pageCSP}, {"X-Frame-Options", "DENY"}}})
	}
	out = append(out,
		rule{"/reports/*", []header{{"Content-Security-Policy", demoCSP}, {"X-Frame-Options", "DENY"}}},
		rule{"/assets/*", []header{{"Cache-Control", "public, max-age=31536000, immutable"}}},
		rule{"/images/*", []header{{"Cache-Control", "public, max-age=86400"}}},
	)
	return out
}

// cloudflareHeaders renders public/_headers for Cloudflare Workers static
// assets.
func cloudflareHeaders() []byte {
	var b strings.Builder
	b.WriteString("# Generated by scripts/site from scripts/site/headers.go. Do not edit.\n")
	for _, r := range rules() {
		b.WriteString("\n" + r.Pattern + "\n")
		for _, h := range r.Headers {
			b.WriteString("  " + h.Key + ": " + h.Value + "\n")
		}
	}
	return []byte(b.String())
}

// vercelConfig renders site/vercel.json. The Vercel project's root
// directory must be set to site/ in its settings.
func vercelConfig() ([]byte, error) {
	type kv struct {
		Key   string `json:"key"`
		Value string `json:"value"`
	}
	type source struct {
		Source  string `json:"source"`
		Headers []kv   `json:"headers"`
	}
	var headers []source
	for _, r := range rules() {
		s := source{Source: vercelSource(r.Pattern)}
		for _, h := range r.Headers {
			s.Headers = append(s.Headers, kv{h.Key, h.Value})
		}
		headers = append(headers, s)
	}
	out, err := json.MarshalIndent(map[string]any{
		"$schema":         "https://openapi.vercel.sh/vercel.json",
		"framework":       nil,
		"installCommand":  "",
		"outputDirectory": "public",
		// Matches Cloudflare's default: /features redirects to /features/.
		"trailingSlash": true,
		"headers":       headers,
	}, "", "  ")
	return append(out, '\n'), err
}

// vercelSource converts a Cloudflare pattern: a trailing /* becomes
// /(.*). Exact paths are the same on both hosts.
func vercelSource(pattern string) string {
	if strings.HasSuffix(pattern, "/*") {
		return strings.TrimSuffix(pattern, "*") + "(.*)"
	}
	return pattern
}
