// Command notices writes THIRD_PARTY_NOTICES.md: the licence of every Go
// module compiled into tfviz and every web package bundled into reports.
// It fails on licences outside the permissive allowlist. Run `make web`
// first so the web notices exist.
package main

import (
	"bufio"
	"bytes"
	"errors"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
)

var licenceFile = regexp.MustCompile(`(?i)^(licen[cs]e|copying|notice)(\.(md|txt))?$`)

func main() {
	out := "THIRD_PARTY_NOTICES.md"
	if len(os.Args) > 1 {
		out = os.Args[1]
	}
	if err := run(out); err != nil {
		fmt.Fprintln(os.Stderr, "notices:", err)
		os.Exit(1)
	}
}

type module struct{ path, version, dir string }

func run(out string) error {
	modules, err := binaryModules()
	if err != nil {
		return err
	}
	var b strings.Builder
	b.WriteString("# Third-party notices\n\n<!-- Generated by scripts/notices (make notices). Do not edit. -->\n\n")
	b.WriteString("tfviz includes the following third-party software. Reports generated by tfviz embed only the web packages listed in the second section.\n\n## Go modules in the tfviz binary\n")
	for _, m := range modules {
		files, err := licenceFiles(m.dir)
		if err != nil {
			return err
		}
		if len(files) == 0 {
			return fmt.Errorf("%s has no licence file", m.path)
		}
		kind, err := identify(files)
		if err != nil {
			return fmt.Errorf("%s: %w", m.path, err)
		}
		fmt.Fprintf(&b, "\n### %s %s (%s)\n", m.path, m.version, kind)
		for _, f := range files {
			text, _ := os.ReadFile(f)
			fmt.Fprintf(&b, "\n```text\n%s\n```\n", strings.TrimSpace(string(text)))
		}
	}
	web, err := os.ReadFile("web/dist/THIRD_PARTY_NOTICES.txt")
	if err != nil {
		return errors.New("web notices are missing; run `make web` first")
	}
	fmt.Fprintf(&b, "\n## Web packages embedded in every report\n\n```text\n%s\n```\n", strings.TrimSpace(string(web)))
	return os.WriteFile(out, []byte(b.String()), 0o644)
}

// binaryModules lists the modules linked into cmd/tfviz, excluding tfviz itself.
func binaryModules() ([]module, error) {
	cmd := exec.Command("go", "list", "-deps", "-f", `{{with .Module}}{{if not .Main}}{{.Path}} {{.Version}} {{.Dir}}{{end}}{{end}}`, "./cmd/tfviz")
	cmd.Stderr = os.Stderr
	data, err := cmd.Output()
	if err != nil {
		return nil, err
	}
	seen := map[string]module{}
	scanner := bufio.NewScanner(bytes.NewReader(data))
	for scanner.Scan() {
		fields := strings.Fields(scanner.Text())
		if len(fields) == 3 {
			seen[fields[0]] = module{fields[0], fields[1], fields[2]}
		}
	}
	modules := make([]module, 0, len(seen))
	for _, m := range seen {
		modules = append(modules, m)
	}
	sort.Slice(modules, func(i, j int) bool { return modules[i].path < modules[j].path })
	return modules, nil
}

func licenceFiles(dir string) ([]string, error) {
	entries, err := os.ReadDir(dir)
	if err != nil {
		return nil, err
	}
	var files []string
	for _, e := range entries {
		if !e.IsDir() && licenceFile.MatchString(e.Name()) {
			files = append(files, filepath.Join(dir, e.Name()))
		}
	}
	sort.Strings(files)
	return files, nil
}

// identify recognises the permissive licences tfviz accepts.
func identify(files []string) (string, error) {
	var all strings.Builder
	for _, f := range files {
		text, err := os.ReadFile(f)
		if err != nil {
			return "", err
		}
		all.Write(text)
	}
	text := all.String()
	switch {
	case strings.Contains(text, "Apache License") && strings.Contains(text, "Version 2.0"):
		return "Apache-2.0", nil
	case strings.Contains(text, "Permission is hereby granted, free of charge"):
		return "MIT", nil
	case strings.Contains(text, "Redistribution and use in source and binary forms"):
		return "BSD", nil
	case strings.Contains(text, "Permission to use, copy, modify, and/or distribute"):
		return "ISC", nil
	}
	return "", errors.New("licence not recognised as Apache-2.0, MIT, BSD or ISC; review it before release")
}
